name: CI/CD Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install dependencies directly without requirements.txt
        pip install flask pymongo pytest pytest-mock mongomock pytest-cov
    
    - name: Run tests with coverage
      run: |
        cd web_app
        python -m pytest tests/ --cov=back_end --cov=front_end --cov-report=xml --cov-report=term-missing --cov-fail-under=80
    
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: web_app/coverage.xml
        if-no-files-found: error