name: Recipe App Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo flask python-dotenv pytest pytest-cov

      - name: Setup test database
        run: |
          python -c "
          from pymongo import MongoClient
          client = MongoClient('mongodb://localhost:27017/')
          db = client['recipe_database']
          db['recipes'].insert_one({
              'name': 'Mock Recipe',
              'minutes': 30,
              'nutrition': {'calories': 400},
              'ingredients': ['ingredient1'],
              'tags': ['lunch', 'main-dish', 'easy']
          })
          db.create_collection('saved_recipes')
          print('Database setup complete')
          "

      - name: Run tests with coverage
        run: |
          echo "Running pytest on recipe-recommender-test, recipe-system-test, mongo-connection-test"
          pytest tests/recipe-recommender-test.py \
                 tests/recipe-system-test.py \
                 tests/mongo-connection-test.py \
                 --cov=back_end \
                 --cov-report=term-missing \
                 --cov-fail-under=80
